export const _SEMANTIC = {
  transitionDuration: '0.2s',
  disabledOpacity: '0.6',
  iconSize: '1rem',
  anchorGutter: '2px',
  focusRing: {
    width: '1px',
    style: 'solid',
    color: '{primary.color}',
    offset: '2px',
    shadow: 'none',
  },
  formField: {
    paddingX: '0.875rem',
    paddingY: '0.75rem',
    sm: {
      fontSize: '0.875rem',
      paddingX: '0.75rem',
      paddingY: '0.625rem',
    },
    lg: {
      fontSize: '1.125rem',
      paddingX: '1rem',
      paddingY: '0.875rem',
    },
    borderRadius: '{border.radius.md}',
    focusRing: {
      width: '0',
      style: 'none',
      color: 'transparent',
      offset: '0',
      shadow: 'none',
    },
    transitionDuration: '{transition.duration}',
  },
  list: {
    padding: '0.25rem 0.25rem',
    gap: '2px',
    header: {
      padding: '0.5rem 1rem 0.25rem 1rem',
    },
    option: {
      padding: '0.5rem 0.75rem',
      borderRadius: '{border.radius.sm}',
    },
    optionGroup: {
      padding: '0.5rem 0.75rem',
      fontWeight: '600',
    },
  },
  content: {
    borderRadius: '{border.radius.md}',
  },
  mask: {
    transitionDuration: '0.15s',
  },
  overlay: {
    select: {
      borderRadius: '{border.radius.md}',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
    popover: {
      borderRadius: '{border.radius.md}',
      padding: '0.938rem',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
    modal: {
      borderRadius: '{border.radius.xl}',
      padding: '1.25rem',
      shadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
    },
    navigation: {
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
  },
  navigation: {
    list: {
      padding: '0.25rem 0.25rem',
      gap: '2px',
    },
    item: {
      padding: '0.5rem 0.75rem',
      borderRadius: '{border.radius.sm}',
      gap: '0.5rem',
    },
    submenuLabel: {
      padding: '0.5rem 0.75rem',
      fontWeight: '600',
    },
    submenuIcon: {
      size: '0.875rem',
    },
  },
  colorScheme: {
    light: {
      surface: {
        0: '#ffffff',
        50: '{gray.50}',
        100: '{gray.100}',
        200: '{gray.200}',
        300: '{gray.300}',
        400: '{gray.400}',
        500: '{gray.500}',
        600: '{gray.600}',
        700: '{gray.700}',
        800: '{gray.800}',
        900: '{gray.900}',
        950: '{gray.950}',
      },
      primary: {
        50: '{blue.50}',
        100: '{blue.100}',
        200: '{blue.200}',
        300: '{blue.300}',
        400: '{blue.400}',
        500: '{blue.500}',
        600: '{blue.600}',
        700: '{blue.700}',
        800: '{blue.800}',
        900: '{blue.900}',
        950: '{blue.950}',
        color: '{primary.500}',
        contrastColor: '{surface.0}',
        hoverColor: '{primary.600}',
        activeColor: '{primary.600}',
      },
      text: {
        color: '{surface.700}',
        hoverColor: '{surface.900}',
        mutedColor: '{surface.500}',
        hoverMutedColor: '{surface.600}',
      },
      formField: {
        background: '{surface.50}',
        disabledBackground: 'color-mix(in oklab, {surface.500} 40%, transparent)',
        placeholderColor: 'color-mix(in oklab, {surface.700} 80%, transparent)',
        filledBackground: '{surface.50}',
        filledHoverBackground: '{surface.100}',
        filledFocusBackground: '{surface.100}',
        floatLabelColor: '{surface.600}',
        floatLabelFocusColor: '{surface.600}',
        floatLabelActiveColor: '{surface.600}',
        floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
        invalidPlaceholderColor: '{red.500}',
        color: '{surface.600}',
        borderColor: '{surface.300}',
        hoverBorderColor: '{surface.400}',
        invalidBorderColor: '{red.500}',
        focusBorderColor: '{primary.color}',
        disabledColor: '{surface.900}',
        iconColor: '{surface.500}',
        shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
      },
    },
    dark: {
      surface: {
        0: '#ffffff',
        50: '{neutral.50}',
        100: '{neutral.100}',
        200: '{neutral.200}',
        300: '{neutral.300}',
        400: '{neutral.400}',
        500: '{neutral.500}',
        600: '{neutral.600}',
        700: '{neutral.700}',
        800: '{neutral.800}',
        900: '{neutral.900}',
        950: '{neutral.950}',
      },
      primary: {
        50: '{fuchsia.50}',
        100: '{fuchsia.100}',
        200: '{fuchsia.200}',
        300: '{fuchsia.300}',
        400: '{fuchsia.400}',
        500: '{fuchsia.500}',
        600: '{fuchsia.600}',
        700: '{fuchsia.700}',
        800: '{fuchsia.800}',
        900: '{fuchsia.900}',
        950: '{fuchsia.950}',
        color: '{primary.500}',
        contrastColor: '{primary.50}',
        hoverColor: '{primary.600}',
        activeColor: '{primary.700}',
      },
      text: {
        color: '{surface.0}',
        hoverColor: '{surface.0}',
        mutedColor: '{surface.500}',
        hoverMutedColor: '{surface.600}',
      },
      formField: {
        background: '{surface.700}',
        disabledBackground: 'color-mix(in oklab, {surface.300} 60%, transparent)',
        placeholderColor: 'color-mix(in oklab, {surface.0} 80%, transparent)',
        filledBackground: '{surface.600}',
        filledHoverBackground: '{surface.600}',
        filledFocusBackground: '{surface.700}',
        floatLabelColor: '{surface.0}',
        floatLabelFocusColor: '{surface.0}',
        floatLabelActiveColor: '{surface.0}',
        floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
        invalidPlaceholderColor: '{red.500}',
        color: '{surface.0}',
        borderColor: '{surface.400}',
        hoverBorderColor: '{surface.300}',
        invalidBorderColor: '{red.500}',
        focusBorderColor: '{primary.color}',
        disabledColor: '{surface.500}',
        floatLabelOnActiveBackground: 'red',
        iconColor: '{surface.300}',
        shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
      },
      content: {
        background: '{surface.700}',
        hoverBackground: '{surface.100}',
        borderColor: '{surface.500}',
        color: '{text.color}',
        hoverColor: '{text.hover.color}',
      },
    },
  },
};

/* colorScheme: {
    root:{
      
    },
    light: {
      surface: {
        0: '#ffffff',
        50: '{gray.50}',
        100: '{gray.100}',
        200: '{gray.200}',
        300: '{gray.300}',
        400: '{gray.400}',
        500: '{gray.500}',
        600: '{gray.600}',
        700: '{gray.700}',
        800: '{gray.800}',
        900: '{gray.900}',
        950: '{gray.950}',
      },
      
      headerBackground: '{surface.200}',
      borderBottomColor: '{surface.600}', 
      primary: {
        50: '{blue.50}',
        100: '{blue.100}',
        200: '{blue.200}',
        300: '{blue.300}',
        400: '{blue.400}',
        500: '{blue.500}',
        600: '{blue.600}',
        700: '{blue.700}',
        800: '{blue.800}',
        900: '{blue.900}',
        950: '{blue.950}',
        color: '{primary.500}',
        contrastColor: '{surface.0}',
        hoverColor: '{primary.600}',
        activeColor: '{primary.600}',
      },
      highlight: {
        background: '{primary.50}',
        focusBackground: '{primary.100}',
        color: '{primary.700}',
        focusColor: '{primary.800}',
      },
      mask: {
        background: 'rgba(0,0,0,0.4)',
        color: '{surface.200}',
      },
      formField: {
        background: '{surface.100}',
        disabledBackground: '{surface.600}',
        filledBackground: 'color-mix(in oklab, {surface.300} 30%, transparent)',
        filledHoverBackground: 'color-mix(in oklab, {surface.300} 50%, transparent)',
        filledFocusBackground: 'color-mix(in oklab, {surface.300} 30%, transparent)',
        borderColor: '{surface.600}',
        hoverBorderColor: '{surface.600}',
        focusBorderColor: '{primary.color}',
        invalidBorderColor: '{red.500}',
        color: '{surface.950}',
        disabledColor: '{surface.500}',
        placeholderColor: '{surface.800}',
        invalidPlaceholderColor: '{red.500}',
        floatLabelColor: '{surface.900}',
        floatLabelFocusColor: '{primary.600}',
        floatLabelActiveColor: '{surface.900}',
        floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
        floatLabelOnActiveBackground: 'red',
        iconColor: '{surface.800}',
        shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
         filled: {
          background: 'color-mix(in oklab, {surface.300} 30%, transparent)',
          focusBackground: 'color-mix(in oklab, {surface.300} 30%, transparent)',
        }, 
      },
      text: {
        color: '{surface.900}',
        hoverColor: '{surface.800}',
        mutedColor: '{surface.500}',
        hoverMutedColor: '{surface.600}',
      },
      content: {
        background: '{surface.0}',
        hoverBackground: '{surface.100}',
        borderColor: '{surface.500}',
        color: '{text.color}',
        hoverColor: '{text.hover.color}',
      },
      overlay: {
        select: {
          background: '{surface.0}',
          borderColor: '{surface.200}',
          color: '{text.color}',
        },
        popover: {
          background: '{surface.0}',
          borderColor: '{surface.200}',
          color: '{text.color}',
        },
        modal: {
          background: '{surface.0}',
          borderColor: '{surface.200}',
          color: '{text.color}',
        },
      },
      list: {
        option: {
          focusBackground: '{surface.100}',
          selectedBackground: '{highlight.background}',
          selectedFocusBackground: '{highlight.focus.background}',
          color: '{text.color}',
          focusColor: '{text.hover.color}',
          selectedColor: '{highlight.color}',
          selectedFocusColor: '{highlight.focus.color}',
          icon: {
            color: '{surface.400}',
            focusColor: '{surface.500}',
          },
        },
        optionGroup: {
          background: 'transparent',
          color: '{text.muted.color}',
        },
      },
      navigation: {
        item: {
          focusBackground: '{surface.100}',
          activeBackground: '{surface.100}',
          color: '{text.color}',
          focusColor: '{text.hover.color}',
          activeColor: '{text.hover.color}',
          icon: {
            color: '{surface.400}',
            focusColor: '{surface.500}',
            activeColor: '{surface.500}',
          },
        },
        submenuLabel: {
          background: 'transparent',
          color: '{text.muted.color}',
        },
        submenuIcon: {
          color: '{surface.400}',
          focusColor: '{surface.500}',
          activeColor: '{surface.500}',
        },
      },
    },
    dark: {
      surface: {
        0: '#ffffff',
        50: '{slate.50}',
        100: '{slate.100}',
        200: '{slate.200}',
        300: '{slate.300}',
        400: '{slate.400}',
        500: '{slate.500}',
        600: '{slate.600}',
        700: '{slate.700}',
        800: '{slate.800}',
        900: '{slate.900}',
        950: '{slate.950}',
      },
      
      headerBackground: '{surface.600}',
      borderBottomColor: '{surface.300}', 
      primary: {
        50: '{fuchsia.50}',
        100: '{fuchsia.100}',
        200: '{fuchsia.200}',
        300: '{fuchsia.300}',
        400: '{fuchsia.400}',
        500: '{fuchsia.500}',
        600: '{fuchsia.600}',
        700: '{fuchsia.700}',
        800: '{fuchsia.800}',
        900: '{fuchsia.900}',
        950: '{fuchsia.950}',
        color: '{primary.500}',
        contrastColor: '{primary.50}',
        hoverColor: '{primary.600}',
        activeColor: '{primary.700}',
      },
      highlight: {
        background: 'red',
        focusBackground: '{primary.100}',
        color: '{primary.700}',
        focusColor: '{primary.800}',
      },
      text: {
        color: '{surface.0}',
        hoverColor: '{surface.800}',
        mutedColor: '{surface.500}',
        hoverMutedColor: '{surface.600}',
      },
      content: {
        background: '{surface.900}',
        hoverBackground: '{surface.100}',
        borderColor: '{surface.500}',
        color: '{text.color}',
        hoverColor: '{text.hover.color}',
      },
      formField: {
        background: '{surface.800}',
        
        disabledBackground: '{surface.600}',
        filledBackground: '{surface.500}',
        filledHoverBackground: '{surface.500}',
        filledFocusBackground: '{surface.500}',
        borderColor: '{surface.600}',
        hoverBorderColor: '{surface.600}',
        focusBorderColor: '{primary.color}',
        invalidBorderColor: '{red.400}',
        color: '{surface.0}',
        disabledColor: '{surface.500}',
        placeholderColor: '{surface.100}',
        invalidPlaceholderColor: '{red.400}',
        floatLabelColor: '{surface.500}',
        floatLabelFocusColor: '{primary.600}',
        floatLabelActiveColor: '{surface.500}',
        floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
        iconColor: '{surface.100}',
        shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)', 
      },
    },
  },
  */
