export const _SEMANTIC = {
  transitionDuration: '0.2s',
  disabledOpacity: '0.6',
  iconSize: '1rem',
  anchorGutter: '2px',
  /* primary: {
    50: '{fuchsia.50}',
    100: '{fuchsia.100}',
    200: '{fuchsia.200}',
    300: '{fuchsia.300}',
    400: '{fuchsia.400}',
    500: '{fuchsia.500}',
    600: '{fuchsia.600}',
    700: '{fuchsia.700}',
    800: '{fuchsia.800}',
    900: '{fuchsia.900}',
    950: '{fuchsia.950}',
  }, */
  formField: {
    paddingX: '1.25rem',
    paddingY: '0.5rem',
    sm: {
      fontSize: '0.875rem',
      paddingX: '0.75rem',
      paddingY: '0.375rem',
    },
    lg: {
      fontSize: '1.125rem',
      paddingX: '1.8rem',
      paddingY: '0.725rem',
    },
    borderRadius: '{border.radius.md}',
    focusRing: {
      width: '0',
      style: 'none',
      color: 'transparent',
      offset: '0',
      shadow: 'none',
    },
    transitionDuration: '{transition.duration}',
  },
  content: {
    borderRadius: '{border.radius.md}',
  },
  overlay: {
    select: {
      borderRadius: '{border.radius.md}',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
    popover: {
      borderRadius: '{border.radius.md}',
      padding: '0.938rem',
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
    modal: {
      borderRadius: '{border.radius.xl}',
      padding: '1.25rem',
      shadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
    },
    navigation: {
      shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    },
  },
  colorScheme: {
    light: {
      surface: {
        0: '#ffffff',
        50: '#ffffff',
        100: '#fefefe',
        200: '#fcfdfd',
        300: '#fbfcfd',
        400: '#fafbfc',
        500: '#f9fafb',
        600: '#d4d5d5',
        700: '#aeafb0',
        800: '#898a8a',
        900: '#646464',
        950: '#3e3f3f',
      },
      bodyBackground: '{surface.500}',
      headerBackground: '{surface.200}',
      borderBottomColor: '{surface.600}',
      primary: {
        50: '{blue.50}',
        100: '{blue.100}',
        200: '{blue.200}',
        300: '{blue.300}',
        400: '{blue.400}',
        500: '{blue.500}',
        600: '{blue.600}',
        700: '{blue.700}',
        800: '{blue.800}',
        900: '{blue.900}',
        950: '{blue.950}',
        color: '{primary.500}',
        contrastColor: '{surface.0}',
        hoverColor: '{primary.600}',
        activeColor: '{primary.700}',
      },
      highlight: {
        background: '{primary.50}',
        focusBackground: '{primary.100}',
        color: '{primary.700}',
        focusColor: '{primary.800}',
      },
      mask: {
        background: 'rgba(0,0,0,0.4)',
        color: '{surface.200}',
      },
      formField: {
        background: '{surface.500}',
        disabledBackground: '{surface.600}',
        filledBackground: '{surface.500}',
        filledHoverBackground: '{surface.500}',
        filledFocusBackground: '{surface.500}',
        borderColor: '{surface.600}',
        hoverBorderColor: '{surface.600}',
        focusBorderColor: '{primary.color}',
        invalidBorderColor: '{red.500}',
        color: '{surface.950}',
        disabledColor: '{surface.500}',
        placeholderColor: '{surface.800}',
        invalidPlaceholderColor: '{red.500}',
        floatLabelColor: '{surface.500}',
        floatLabelFocusColor: '{primary.600}',
        floatLabelActiveColor: '{surface.500}',
        floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
        iconColor: '{surface.800}',
        shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
      },
      text: {
        color: '{surface.900}',
        hoverColor: '{surface.800}',
        mutedColor: '{surface.500}',
        hoverMutedColor: '{surface.600}',
      },
      content: {
        background: '{surface.0}',
        hoverBackground: '{surface.100}',
        borderColor: '{surface.200}',
        color: '{text.color}',
        hoverColor: '{text.hover.color}',
      },
      overlay: {
        select: {
          background: '{surface.0}',
          borderColor: '{surface.200}',
          color: '{text.color}',
        },
        popover: {
          background: '{surface.0}',
          borderColor: '{surface.200}',
          color: '{text.color}',
        },
        modal: {
          background: '{surface.0}',
          borderColor: '{surface.200}',
          color: '{text.color}',
        },
      },
      list: {
        option: {
          focusBackground: '{surface.100}',
          selectedBackground: '{highlight.background}',
          selectedFocusBackground: '{highlight.focus.background}',
          color: '{text.color}',
          focusColor: '{text.hover.color}',
          selectedColor: '{highlight.color}',
          selectedFocusColor: '{highlight.focus.color}',
          icon: {
            color: '{surface.400}',
            focusColor: '{surface.500}',
          },
        },
        optionGroup: {
          background: 'transparent',
          color: '{text.muted.color}',
        },
      },
      navigation: {
        item: {
          focusBackground: '{surface.100}',
          activeBackground: '{surface.100}',
          color: '{text.color}',
          focusColor: '{text.hover.color}',
          activeColor: '{text.hover.color}',
          icon: {
            color: '{surface.400}',
            focusColor: '{surface.500}',
            activeColor: '{surface.500}',
          },
        },
        submenuLabel: {
          background: 'transparent',
          color: '{text.muted.color}',
        },
        submenuIcon: {
          color: '{surface.400}',
          focusColor: '{surface.500}',
          activeColor: '{surface.500}',
        },
      },
    },
    dark: {
      surface: {
        0: '#ffffff',
        50: '{slate.50}',
        100: '{slate.100}',
        200: '{slate.200}',
        300: '{slate.300}',
        400: '{slate.400}',
        500: '{slate.500}',
        600: '{slate.600}',
        700: '{slate.700}',
        800: '{slate.800}',
        900: '{slate.900}',
        950: '{slate.950}',
      },
      bodyBackground: '{surface.800}',
      headerBackground: '{surface.600}',
      borderBottomColor: '{surface.300}',
      primary: {
        50: '{fuchsia.50}',
        100: '{fuchsia.100}',
        200: '{fuchsia.200}',
        300: '{fuchsia.300}',
        400: '{fuchsia.400}',
        500: '{fuchsia.500}',
        600: '{fuchsia.600}',
        700: '{fuchsia.700}',
        800: '{fuchsia.800}',
        900: '{fuchsia.900}',
        950: '{fuchsia.950}',
        color: '{primary.500}',
        contrastColor: '{primary.50}',
        hoverColor: '{primary.600}',
        activeColor: '{primary.700}',
      },
      highlight: {
        background: 'red',
        focusBackground: '{primary.100}',
        color: '{primary.700}',
        focusColor: '{primary.800}',
      },
      text: {
        color: '{surface.0}',
        hoverColor: '{surface.800}',
        mutedColor: '{surface.500}',
        hoverMutedColor: '{surface.600}',
      },
      content: {
        background: '{surface.900}',
        hoverBackground: '{surface.100}',
        borderColor: '{surface.500}',
        color: '{text.color}',
        hoverColor: '{text.hover.color}',
      },
      /* formField: {
        background: '{surface.500}',
        disabledBackground: '{surface.600}',
        filledBackground: '{surface.500}',
        filledHoverBackground: '{surface.500}',
        filledFocusBackground: '{surface.500}',
        borderColor: '{surface.600}',
        hoverBorderColor: '{surface.600}',
        focusBorderColor: '{primary.color}',
        invalidBorderColor: '{red.400}',
        color: '{surface.0}',
        disabledColor: '{surface.500}',
        placeholderColor: '{surface.100}',
        invalidPlaceholderColor: '{red.400}',
        floatLabelColor: '{surface.500}',
        floatLabelFocusColor: '{primary.600}',
        floatLabelActiveColor: '{surface.500}',
        floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
        iconColor: '{surface.100}',
        shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
      }, */
    },
  },
};

/* primary: {
        50: '{indigo.50}',
        100: '{indigo.100}',
        200: '{indigo.200}',
        300: '{indigo.300}',
        400: '{indigo.400}',
        500: '{indigo.500}',
        600: '{indigo.600}',
        700: '{indigo.700}',
        800: '{indigo.800}',
        900: '{indigo.900}',
        950: '{indigo.950}',
      },
      surface: {
        0: '#ffffff',
        50: '{neutral.50}',
        100: '{neutral.100}',
        200: '{neutral.200}',
        300: '{neutral.300}',
        400: '{neutral.400}',
        500: '{neutral.500}',
        600: '{neutral.600}',
        700: '{neutral.700}',
        800: '{neutral.800}',
        900: '{neutral.900}',
        950: '{neutral.950}',
      },
      formField: {
        invalidBorderColor: '{red.500}',
        invalidPlaceholderColor: '{red.500}',
      }, */
